// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricsCollection_UpdateMetrics_FullMethodName = "/rpc.MetricsCollection/UpdateMetrics"
)

// MetricsCollectionClient is the client API for MetricsCollection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsCollectionClient interface {
	UpdateMetrics(ctx context.Context, in *BatchUpdateMetricsRequest, opts ...grpc.CallOption) (*BatchUpdateMetricsResponse, error)
}

type metricsCollectionClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsCollectionClient(cc grpc.ClientConnInterface) MetricsCollectionClient {
	return &metricsCollectionClient{cc}
}

func (c *metricsCollectionClient) UpdateMetrics(ctx context.Context, in *BatchUpdateMetricsRequest, opts ...grpc.CallOption) (*BatchUpdateMetricsResponse, error) {
	out := new(BatchUpdateMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsCollection_UpdateMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsCollectionServer is the server API for MetricsCollection service.
// All implementations must embed UnimplementedMetricsCollectionServer
// for forward compatibility
type MetricsCollectionServer interface {
	UpdateMetrics(context.Context, *BatchUpdateMetricsRequest) (*BatchUpdateMetricsResponse, error)
	mustEmbedUnimplementedMetricsCollectionServer()
}

// UnimplementedMetricsCollectionServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsCollectionServer struct {
}

func (UnimplementedMetricsCollectionServer) UpdateMetrics(context.Context, *BatchUpdateMetricsRequest) (*BatchUpdateMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetrics not implemented")
}
func (UnimplementedMetricsCollectionServer) mustEmbedUnimplementedMetricsCollectionServer() {}

// UnsafeMetricsCollectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsCollectionServer will
// result in compilation errors.
type UnsafeMetricsCollectionServer interface {
	mustEmbedUnimplementedMetricsCollectionServer()
}

func RegisterMetricsCollectionServer(s grpc.ServiceRegistrar, srv MetricsCollectionServer) {
	s.RegisterService(&MetricsCollection_ServiceDesc, srv)
}

func _MetricsCollection_UpdateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsCollectionServer).UpdateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsCollection_UpdateMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsCollectionServer).UpdateMetrics(ctx, req.(*BatchUpdateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsCollection_ServiceDesc is the grpc.ServiceDesc for MetricsCollection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsCollection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MetricsCollection",
	HandlerType: (*MetricsCollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMetrics",
			Handler:    _MetricsCollection_UpdateMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server.proto",
}
